name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: tfm-dev-433217
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use Google Artifact Registry
      run: gcloud auth configure-docker europe-southwest1-docker.pkg.dev

    - name: Build the Docker image
      run: docker build -t app-trafico .

    - name: Tag Docker image
      run: docker tag app-trafico europe-southwest1-docker.pkg.dev/tfm-dev-433217/trafico-image-repo/app-trafico:latest

    - name: Push Docker image to Google Artifact Registry
      run: docker push europe-southwest1-docker.pkg.dev/tfm-dev-433217/trafico-image-repo/app-trafico:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy app-trafico \
          --image europe-southwest1-docker.pkg.dev/tfm-dev-433217/your-repository/your-image-name:latest \
          --cpu=1 \
          --region=europe-southwest1 \
          --project=tfm-dev-433217 \
           && gcloud run services update-traffic app-trafico --to-latest
